export const targets = [
    {
        id: 1,
        name: 'apple',
    }, {
        id: 2,
        name: 'banana',
    }, {
        id: 3,
        name: 'bean',
    }, {
        id: 4,
        name: 'beet',
    }, {
        id: 5,
        name: 'blueberry',
    }, {
        id: 6,
        name: 'broccoli',
    }, {
        id: 7,
        name: 'cabbage',
    }, {
        id: 8,
        name: 'carrot',
    }, {
        id: 9,
        name: 'cherry',
    }, {
        id: 10,
        name: 'coconut',
    }, {
        id: 11,
        name: 'corn',
    }, {
        id: 12,
        name: 'cucumber',
    }, {
        id: 13,
        name: 'eggplant',
    }, {
        id: 14,
        name: 'garlic',
    }, {
        id: 15,
        name: 'grapes',
    }, {
        id: 16,
        name: 'lemon',
    }, {
        id: 17,
        name: 'mango',
    }, {
        id: 18,
        name: 'melon',
    }, {
        id: 19,
        name: 'onion',
    }, {
        id: 20,
        name: 'orange',
    }, {
        id: 21,
        name: 'pear',
    }, {
        id: 22,
        name: 'peas',
    }, {
        id: 23,
        name: 'pepper',
    }, {
        id: 24,
        name: 'pineapple',
    }, {
        id: 25,
        name: 'pumpkin',
    }, {
        id: 26,
        name: 'radish',
    }, {
        id: 27,
        name: 'raspberry',
    }, {
        id: 28,
        name: 'strawberry',
    }, {
        id: 29,
        name: 'tomato',
    }, {
        id: 30,
        name: 'watermelon',
    }];